### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by StuKit** [ambr0sial/femboyaccess#2]
j'arrive pas vraiment a trouver le problème, appart que c'est lié au package discord

(Version Python : 3.8, discord.py : 2.3.1)

﻿

C:\Users\user\Desktop\fmbo>built_femboyaccess.py [2023-09-30 20:00:35] [INFO
] discord.client: logging in using static token
[2023-09-30 20:00:36] [ERROR ] discord.client: Ignoring exception in on_disconnect
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 441, in _run_event await coro(*args, **kwargs)
File "C:\Users\user\Desktop\fmbo\built_femboyaccess.py", line 1263, in on_disconnect
await channel.send(await femboyaccess("disconnected", "this session is disconnected (unusable)! :3")) NameError: name 'channel' is not defined
Traceback (most recent call last):
File "C:\Users\user\Desktop\fmbo\built_femboyaccess.py", line 1267, in <module>
client.run(token)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 860, in run
asyncio.run(runner())
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run return loop.run_until_complete(main)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete return future.result()
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 849, in runner await self.start(token, reconnect-reconnect)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 778, in start await self.connect(reconnect=reconnect)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 704, in connect
raise Privileged IntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/a pplications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del____ at 0x000002349414AC10>
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del____
self.close()
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close self._loop.call_soon(self._call_connection_lost, None)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
self._check_closed()
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
C:\Users\user\Desktop\fmbo>

**Comment by ambr0sial** [comment]
coucou! de ce que je vois t'as oublié d'activer les intents de ton bot, il faut que t'ailles sur le [developer portal](https://discord.dev), et dans la catégorie `Bot`, sous `Privileged Gateway Intents`, coche les trois options

**Comment by StuKit** [comment]
ah effectivement, je m'excuse du dérangement x)

**Comment by ambr0sial** [comment]
no worries!! dis-moi si y a des trucs qui marchent pas btw, j'ai une mauvaise manie de pas vraiment vérifier de fond en comble avant de release quelque chose-
